# Generated by Django 5.2 on 2025-04-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_location_event_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='final_date',
            field=models.DateTimeField(null=True),
        ),
    ]
