# Generated by Django 5.2 on 2025-04-29 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_event_final_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(null=True)),
                ('is_chosen', models.BooleanField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_options', to='api.event')),
            ],
            options={
                'unique_together': {('event', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='TimeVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('time_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='api.timeoption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
