# Generated by Django 5.2 on 2025-05-02 15:58

from django.db import migrations

def create_default_categories(apps, schema_editor):

    TaskCategory = apps.get_model("api", "TaskCategory")
    User = apps.get_model("api", "CustomUser")

    default_categories = {
        "Logistics": "Securing location, permits, site layout, and accessibility.",
        "Refreshments": "Coordinating meals, dietary needs, and vendor communication.",
        "Equipment": "Arranging necessary items like tables, seating, sound systems, or utensils.",
        "Transportation": "Organizing shuttles, carpooling, and parking plans.",
        "Activities": "Planning the event agenda, activities, games, or guest appearances.",
        "Finance": "Managing expenses, contributions, and payment tracking.",
        "RSVPs & Communication": "Handling invitations, confirmations, reminders, and on-site signage.",
        "Safety": "Ensuring first aid availability and preparing for emergencies or weather disruptions.",
        "Setup": "Coordinating pre-event setup and post-event breakdown.",
        "Media": "Capturing event photos/videos, social media coverage, and sharing post-event highlights."
    }

    creator_of_default_categories = User.objects.filter(is_superuser=True).first()
    if not creator_of_default_categories:
            #For test purposes
            creator_of_default_categories = User.objects.create_superuser(
            username='admin',
            email='admin@example.com',
            password='admin123'
            )

    for category,category_desc in default_categories.items():
        TaskCategory.objects.get_or_create(
            name = category,
            description = category_desc,
            created_by = creator_of_default_categories,
            created_for = None,
            is_default = True,
        )



class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_comment'),
    ]

    operations = [
        migrations.RunPython(create_default_categories)
    ]
