# Generated by Django 5.2 on 2025-05-07 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20250502_1658'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.comment'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='api.event'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_to_id', models.IntegerField()),
                ('related_type', models.CharField(choices=[('event_created', 'Event Created'), ('event_updated', 'Event Updated'), ('event_canceled', 'Event Canceled'), ('event_time_finalized', 'Event Time Finalized'), ('event_invitation', 'Event Invitation'), ('event_reminder', 'Event Reminder'), ('group_created', 'Group Created'), ('group_invitation', 'Group Invitation'), ('group_join_request', 'Group Join Request'), ('group_role_changed', 'Group Role Changed'), ('message_received', 'Message Received'), ('comment_added', 'Comment Added'), ('comment_mention', 'Mentioned in Comment'), ('comment_reply', 'Reply to Comment'), ('comment_liked', 'Comment Liked'), ('friend_request', 'Friend Request'), ('friend_accepted', 'Friend Request Accepted'), ('task_assigned', 'Task Assigned'), ('payment_requested', 'Payment Requested'), ('payment_received', 'Payment Received'), ('system_announcement', 'System Announcement')], max_length=50)),
                ('content', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='api_notific_user_id_48bbdc_idx'), models.Index(fields=['user', 'is_read'], name='api_notific_user_id_16328d_idx'), models.Index(fields=['related_type', 'related_to_id'], name='api_notific_related_942b75_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('event_created', 'Event Created'), ('event_updated', 'Event Updated'), ('event_canceled', 'Event Canceled'), ('event_time_finalized', 'Event Time Finalized'), ('event_invitation', 'Event Invitation'), ('event_reminder', 'Event Reminder'), ('group_created', 'Group Created'), ('group_invitation', 'Group Invitation'), ('group_join_request', 'Group Join Request'), ('group_role_changed', 'Group Role Changed'), ('message_received', 'Message Received'), ('comment_added', 'Comment Added'), ('comment_mention', 'Mentioned in Comment'), ('comment_reply', 'Reply to Comment'), ('comment_liked', 'Comment Liked'), ('friend_request', 'Friend Request'), ('friend_accepted', 'Friend Request Accepted'), ('task_assigned', 'Task Assigned'), ('payment_requested', 'Payment Requested'), ('payment_received', 'Payment Received'), ('system_announcement', 'System Announcement')], max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'notification_type')},
            },
        ),
    ]
